/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.thriving.oss.reactive.kafka.streams

import org.apache.kafka.clients.producer.ProducerConfig
import org.apache.kafka.common.serialization.StringSerializer
import reactor.core.Disposable
import reactor.kafka.receiver.KafkaReceiver
import reactor.kafka.receiver.ReceiverOptions
import reactor.kafka.receiver.ReceiverRecord
import reactor.kafka.sender.KafkaSender
import reactor.kafka.sender.SenderOptions
import reactor.kafka.sender.SenderRecord

class ReactiveStreamsBuilder {
    private val sources = mutableListOf<ReactiveKStream<*, *>>()

    fun <K, V> stream(topic: String): ReactiveKStream<K, V> {
        val stream = ReactiveKStream<K, V>(topic)
        sources.add(stream)
        return stream
    }

    internal fun buildTopology(): ReactiveTopology {
        return ReactiveTopology(sources)
    }
}

class ReactiveKStream<K, V> internal constructor(
    internal val topic: String,
    internal val operations: List<StreamOperation> = emptyList(),
    internal val sinkTopic: String? = null
) {
    fun filter(predicate: (K, V) -> Boolean): ReactiveKStream<K, V> =
        ReactiveKStream(topic, operations + StreamOperation.Filter(predicate as (Any?, Any?) -> Boolean), sinkTopic)

    fun <VR> map(mapper: (K, V) -> VR): ReactiveKStream<K, VR> =
        ReactiveKStream(topic, operations + StreamOperation.Map(mapper as (Any?, Any?) -> Any?), sinkTopic)

    fun to(topic: String): ReactiveKStream<K, V> =
        ReactiveKStream(this.topic, operations, topic)
}

sealed class StreamOperation {
    class Filter(val predicate: (Any?, Any?) -> Boolean) : StreamOperation()
    class Map(val mapper: (Any?, Any?) -> Any?) : StreamOperation()
}

class ReactiveTopology(
    internal val sources: List<ReactiveKStream<*, *>>
)

class ReactiveKafkaStreams(
    private val topology: ReactiveTopology,
    private val props: Map<String, Any>
) {
    private val subscriptions = mutableListOf<Disposable>()
    private val sender by lazy {
        val producerProps = props + mapOf(
            ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java,
            ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java
        )
        KafkaSender.create<String, String>(SenderOptions.create(producerProps))
    }

    fun start() {
        // For each source (stream), create a pipeline
        for (source in topology.sources) {
            // We'll only support String key/values for now for simplicity
            val options = ReceiverOptions.create<String, String>(props)
                .subscription(listOf(source.topic))

            val receiver = KafkaReceiver.create(options)
            var flux = receiver.receive()

            // Apply filter and map operations
            for (op in source.operations) {
                when (op) {
                    is StreamOperation.Filter -> {
                        @Suppress("UNCHECKED_CAST")
                        val predicate = op.predicate as (String?, String?) -> Boolean
                        flux = flux.filter { record -> predicate(record.key(), record.value()) }
                    }
                    is StreamOperation.Map -> {
                        @Suppress("UNCHECKED_CAST")
                        val mapper = op.mapper as (String?, String?) -> Any?
                        flux = flux.map { record ->
                            // Only value is mapped for now
                            val mapped = mapper(record.key(), record.value())
                            record // TODO
                        }
                    }
                }
            }

            if (source.sinkTopic != null) {
                // SINK: Write to another topic
                val outTopic = source.sinkTopic
                val sendFlux = flux.map { record ->
                    SenderRecord.create(outTopic, null, null, record.key(), record.value(), null)
                }
                val disposable = sender.send(sendFlux)
                    .doOnError { e -> println("Send error: $e") }
                    .subscribe { result ->
                        println("Record sent to $outTopic: ${result.correlationMetadata()}")
                    }
                subscriptions += disposable
            } else {
                // No sink: Print to stdout (default)
                val disposable = flux.doOnNext { record ->
                    println("Processed record: ${record.key()} -> ${record.value()}")
                }.subscribe()
                subscriptions += disposable
            }
        }
    }

    fun close() {
        subscriptions.forEach { it.dispose() }
    }
}
