/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Project Reactor
    implementation("io.projectreactor:reactor-core:3.7.8")

    // Reactor Kafka (reactive Kafka client)
    implementation("io.projectreactor.kafka:reactor-kafka:1.3.23")

    // Kafka clients (for configuration compatibility)
    implementation("org.apache.kafka:kafka-clients:3.9.1")

    // SLF4J (logging, required by Kafka and Reactor Kafka)
    implementation("org.slf4j:slf4j-api:2.0.17")

    // Optional: Logging implementation (choose your preferred backend)
    runtimeOnly("org.slf4j:slf4j-simple:2.0.17")

    // Kotlin support (if not present)
    implementation(kotlin("stdlib"))

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
